# Generated by Django 6.0.2 on 2026-02-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
